FROM docker.m.daocloud.io/library/nginx:1.27-alpine
ARG SOURCE_REVISION
LABEL org.opencontainers.image.revision=$SOURCE_REVISION
RUN test -n "$SOURCE_REVISION"
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html
EXPOSE 80
