import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useMemo, useRef, useState } from "react";
import { api, ApiError } from "@/api/client";
import type { AuditEntry, DatabaseResponse, LedgerBody, LedgerStatus, RecordSnapshot } from "@/api/types";
import { LedgerForm } from "@/components/LedgerForm";
import { RecordTable } from "@/components/RecordTable";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { databaseKey, formatMoney, invalidateUserData, storeLocalToday } from "@/lib/user-api";
import { useStore } from "@/stores/StoreProvider";

interface Filters { start: string; end: string; status: "" | LedgerStatus; weather: string; activity_query: string; missing_wash_count: boolean; page: number; page_size: number }
function addDays(date: string, amount: number) { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate() + amount); return value.toISOString().slice(0, 10); }
function monthRange(today: string, offset = 0) { const [year, month] = today.split("-").map(Number); const first = new Date(Date.UTC(year, month - 1 + offset, 1)); const last = offset === 0 ? today : new Date(Date.UTC(year, month + offset, 0)).toISOString().slice(0, 10); return [first.toISOString().slice(0, 10), last] as const; }
export function databaseParams(filters: Filters, includePage = true) { const params = new URLSearchParams(); (["start", "end", "status", "weather", "activity_query"] as const).forEach((key) => { if (filters[key]) params.set(key, String(filters[key])); }); if (filters.missing_wash_count) params.set("missing_wash_count", "true"); if (includePage) { params.set("page", String(filters.page)); params.set("page_size", String(filters.page_size)); } return params; }

export function DatabasePage() {
  const { selected } = useStore(); const client = useQueryClient(); const today = selected ? storeLocalToday(selected) : "";
  const selectedIdRef = useRef(selected?.id); selectedIdRef.current = selected?.id;
  const initial = useMemo<Filters>(() => ({ start: "", end: "", status: "", weather: "", activity_query: "", missing_wash_count: false, page: 1, page_size: 50 }), [selected?.id]);
  const [filters, setFilters] = useState(initial); useEffect(() => setFilters(initial), [initial]);
  const queryString = databaseParams(filters).toString();
  const records = useQuery({ queryKey: selected ? databaseKey(selected.id, queryString) : ["database", "none"], enabled: Boolean(selected), queryFn: () => api<DatabaseResponse>(`/database/${selected!.id}/records?${queryString}`) });
  const history = useQuery({ queryKey: ["database", "history", selected?.id], enabled: Boolean(selected), queryFn: () => api<AuditEntry[]>(`/database/${selected!.id}/history`) });
  const [editing, setEditing] = useState<{ storeId: number; record: RecordSnapshot } | null>(null); const [deleting, setDeleting] = useState<{ storeId: number; record: RecordSnapshot } | null>(null); const [rolling, setRolling] = useState<{ storeId: number; entry: AuditEntry } | null>(null); const [message, setMessage] = useState("");
  useEffect(() => { setEditing(null); setDeleting(null); setRolling(null); setMessage(""); }, [selected?.id]);
  const finish = async (storeId: number) => { if (selectedIdRef.current === storeId) { setMessage("操作成功"); setEditing(null); setDeleting(null); setRolling(null); } await invalidateUserData(client, storeId); await client.invalidateQueries({ queryKey: ["database", "history", storeId], exact: true }); };
  const edit = useMutation({ mutationFn: ({ storeId, date, body }: { storeId: number; date: string; body: LedgerBody }) => api(`/ledger/${storeId}/${date}?overwrite=true`, { method: "PUT", body: JSON.stringify(body) }), onSuccess: (_data, variables) => finish(variables.storeId), onError: (e, variables) => { if (selectedIdRef.current === variables.storeId) setMessage(e instanceof ApiError ? e.detail : "编辑失败"); } });
  const remove = useMutation({ mutationFn: ({ storeId, date }: { storeId: number; date: string }) => api<void>(`/ledger/${storeId}/${date}`, { method: "DELETE" }), onSuccess: (_data, variables) => finish(variables.storeId), onError: (e, variables) => { if (selectedIdRef.current === variables.storeId) setMessage(e instanceof ApiError ? e.detail : "删除失败"); } });
  const rollback = useMutation({ mutationFn: ({ storeId, auditId }: { storeId: number; auditId: number }) => api(`/database/${storeId}/history/${auditId}/rollback`, { method: "POST" }), onSuccess: (_data, variables) => finish(variables.storeId), onError: (e, variables) => { if (selectedIdRef.current === variables.storeId) setMessage(e instanceof ApiError ? e.detail : "回滚失败"); } });
  const update = (values: Partial<Filters>) => setFilters((old) => ({ ...old, ...values, page: values.page ?? 1 }));
  if (!selected) return <section><h1 className="text-2xl font-semibold">数据库</h1><p role="status">请先选择门店。</p></section>;
  return <section className="grid gap-4"><h1 className="text-2xl font-semibold">数据库</h1><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => { const [start, end] = monthRange(today); update({ start, end }); }}>本月</Button><Button variant="outline" onClick={() => { const [start, end] = monthRange(today, -1); update({ start, end }); }}>上月</Button><Button variant="outline" onClick={() => update({ start: addDays(today, -6), end: today })}>最近7天</Button><Button variant="outline" onClick={() => update({ start: addDays(today, -29), end: today })}>最近30天</Button></div>
    <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><label>开始日期<input aria-label="开始日期" type="date" value={filters.start} onChange={(e) => update({ start: e.target.value })} className="w-full rounded border p-2" /></label><label>结束日期<input aria-label="结束日期" type="date" value={filters.end} onChange={(e) => update({ end: e.target.value })} className="w-full rounded border p-2" /></label><label>状态<select aria-label="筛选状态" value={filters.status} onChange={(e) => update({ status: e.target.value as Filters["status"] })} className="w-full rounded border p-2"><option value="">全部</option><option>营业</option><option>休息</option><option>天气停业</option></select></label><label>天气<input aria-label="筛选天气" value={filters.weather} onChange={(e) => update({ weather: e.target.value })} className="w-full rounded border p-2" /></label><label>活动搜索<input aria-label="活动搜索" value={filters.activity_query} onChange={(e) => update({ activity_query: e.target.value })} className="w-full rounded border p-2" /></label><label className="flex items-center gap-2"><input aria-label="缺少洗车数量" type="checkbox" checked={filters.missing_wash_count} onChange={(e) => update({ missing_wash_count: e.target.checked })} />缺少洗车数量</label></div>
    <a role="button" className="w-fit rounded border px-4 py-2" href={`/api/database/${selected.id}/export.xlsx?${databaseParams(filters, false)}`} download>导出 Excel</a>
    {records.isLoading ? <p role="status">加载记录…</p> : records.error ? <p role="alert">{records.error.message}</p> : <><p>{records.data?.total ?? 0} 条 · 合计 {formatMoney(records.data?.sum_daily_revenue ?? "0")}</p><RecordTable records={records.data?.items ?? []} categories={records.data?.categories ?? []} onEdit={(record) => setEditing({ storeId: selected.id, record })} onDelete={(record) => setDeleting({ storeId: selected.id, record })} /></>}
    <div className="flex gap-2"><Button disabled={filters.page <= 1} onClick={() => update({ page: filters.page - 1 })}>上一页</Button><span>第 {filters.page} 页</span><Button disabled={filters.page * filters.page_size >= (records.data?.total ?? 0)} onClick={() => update({ page: filters.page + 1 })}>下一页</Button></div>
    <div><h2 className="text-lg font-semibold">修改历史</h2>{history.isLoading ? <p role="status">加载修改历史…</p> : history.error ? <div role="alert"><span>{history.error.message}</span><button className="ml-2 underline" onClick={() => void history.refetch()}>重试历史记录</button></div> : history.data?.length ? history.data.map((entry) => <div key={entry.id} className="flex items-center gap-2 border-b py-2"><span>{entry.record_date ?? "已删除"} · {entry.operation_type} · {entry.operator_username}</span><Button size="sm" variant="outline" onClick={() => setRolling({ storeId: selected.id, entry })}>回滚 #{entry.id}</Button></div>) : <p>暂无修改历史</p>}</div>
    <Dialog open={Boolean(editing && editing.storeId === selected.id)} onOpenChange={(open) => { if (!open) setEditing(null); }}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>编辑记录</DialogTitle></DialogHeader>{editing && <LedgerForm categories={records.data?.categories ?? []} record={editing.record} onSave={(body) => edit.mutate({ storeId: editing.storeId, date: editing.record.date, body })} saving={edit.isPending} />}</DialogContent></Dialog>
    <AlertDialog open={Boolean(deleting && deleting.storeId === selected.id)} onOpenChange={(open) => { if (!open) setDeleting(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确认删除记录？</AlertDialogTitle><AlertDialogDescription>删除后可通过历史记录回滚。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => deleting && remove.mutate({ storeId: deleting.storeId, date: deleting.record.date })}>确认删除</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <AlertDialog open={Boolean(rolling && rolling.storeId === selected.id)} onOpenChange={(open) => { if (!open) setRolling(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>确认回滚记录？</AlertDialogTitle><AlertDialogDescription>记录将恢复到该历史版本。</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={() => rolling && rollback.mutate({ storeId: rolling.storeId, auditId: rolling.entry.id })}>确认回滚</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    {message && <p role={message === "操作成功" ? "status" : "alert"}>{message}</p>}
  </section>;
}
